version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_NAME: task_manager
    working_dir: /go/src/github.com/edgarvarela24/task-manager-api

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: task_manager
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql